name: MoodleExam Windows Build

on:
  workflow_dispatch: {}

jobs:
  windows:
    uses: ./.github/workflows/make-installer-windows.yml
    with:
      runner: windows-2022
      displayed_name: MoodleExam Windows x64
      msystem: mingw64
      msys_package_env: x86_64
      publish_portable_version: true
      head_sha: ${{ github.sha }}
      build_type: RelWithDebInfo
